version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sprockets
    versions:
    - "> 4.0.0.beta8, < 4.0.1"
  - dependency-name: html-proofer
    versions:
    - 3.18.6
    - 3.19.0
